//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class albums
    {
        public albums()
        {
            this.Photos1 = new HashSet<Photos>();
            this.GRD_AlunoTurma_Photos = new HashSet<GRD_AlunoTurma_Photos>();
            this.GRD_AlunoTurma_Album = new HashSet<GRD_AlunoTurma_Album>();
        }
    
        public int album_id { get; set; }
        public string title { get; set; }
        public string album_desc { get; set; }
        public string place { get; set; }
        public string restricted { get; set; }
        public int user_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public string author { get; set; }
        public Nullable<int> cover_id { get; set; }
        public Nullable<System.DateTime> last_access_date { get; set; }
        public int photo_count { get; set; }
        public string shared { get; set; }
        public string hostname { get; set; }
        public Nullable<System.DateTime> deletion_date { get; set; }
        public Nullable<System.DateTime> dt_ultima_visualizacao { get; set; }
        public Nullable<bool> fl_politica_storage { get; set; }
    
        public virtual Photos Photos { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Photos> Photos1 { get; set; }
        public virtual ICollection<GRD_AlunoTurma_Photos> GRD_AlunoTurma_Photos { get; set; }
        public virtual ICollection<GRD_AlunoTurma_Album> GRD_AlunoTurma_Album { get; set; }
    }
}
