//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Users = new HashSet<Users>();
            this.GRD_Company = new HashSet<GRD_Company>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string isNicephotosLogin { get; set; }
        public System.DateTime dt_include { get; set; }
        public string url_logo { get; set; }
        public string cart_logo { get; set; }
        public string lnkHome { get; set; }
        public string LandingPageURL { get; set; }
        public Nullable<int> UserIDMaster { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<GRD_Company> GRD_Company { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
