//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART_LOG_REFRESH_CACHE
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA_HORA { get; set; }
        public string METODO { get; set; }
    }
}
