//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_Photobook
    {
        public FB_Photobook()
        {
            this.GRD_AlunoTurma_Book = new HashSet<GRD_AlunoTurma_Book>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public int Pages { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public Nullable<System.DateTime> FinalizationDate { get; set; }
        public bool isDeleted { get; set; }
        public int AssemblyStep { get; set; }
        public int SizeID { get; set; }
        public int CoverID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public int PaperID { get; set; }
        public Nullable<int> ThemeID { get; set; }
        public int Type { get; set; }
        public string guid { get; set; }
        public Nullable<int> CurrentPageLeft { get; set; }
        public Nullable<int> CurrentPageRight { get; set; }
        public string Assemble_Type { get; set; }
    
        public virtual ICollection<GRD_AlunoTurma_Book> GRD_AlunoTurma_Book { get; set; }
    }
}
