//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Turma_Preco_Hist
    {
        public GRD_Turma_Preco_Hist()
        {
            this.GRD_Turma_Preco = new HashSet<GRD_Turma_Preco>();
        }
    
        public int ID { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataAtualizacao { get; set; }
    
        public virtual ICollection<GRD_Turma_Preco> GRD_Turma_Preco { get; set; }
    }
}
