//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Turma_Preco
    {
        public int ID { get; set; }
        public int TurmaID { get; set; }
        public int ProductID { get; set; }
        public int Parcela { get; set; }
        public decimal Preco { get; set; }
        public decimal PrecoFoto { get; set; }
        public int TurmaPrecoHistID { get; set; }
    
        public virtual GRD_Turma GRD_Turma { get; set; }
        public virtual GRD_Turma_Preco_Hist GRD_Turma_Preco_Hist { get; set; }
        public virtual Products Products { get; set; }
    }
}
