//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Process_Upload
    {
        public int ID { get; set; }
        public int AlunoTurmaID { get; set; }
        public int UserID { get; set; }
        public int AlbumID { get; set; }
        public string Status { get; set; }
        public string Msg { get; set; }
        public string Path { get; set; }
        public string NameFile { get; set; }
        public decimal Size { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public string PathPhoto { get; set; }
        public System.DateTime PhotoDate { get; set; }
        public int OrderPhoto { get; set; }
        public Nullable<int> InodeID { get; set; }
        public Nullable<int> PhotoID { get; set; }
        public string PhotoDesc { get; set; }
        public string Origem { get; set; }
        public int PageTypeID { get; set; }
        public System.DateTime DtCreated { get; set; }
        public System.DateTime DtLastModified { get; set; }
    }
}
