//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Cheque
    {
        public int ID { get; set; }
        public int AlunoTurmaID { get; set; }
        public int OrderRequestID { get; set; }
        public int OrderID { get; set; }
        public int Parcela { get; set; }
        public string CMC7 { get; set; }
        public string CpfCnpj { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public Nullable<System.DateTime> DataCompensacao { get; set; }
    
        public virtual GRD_OrderRequest GRD_OrderRequest { get; set; }
    }
}
