//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Pacote
    {
        public GRD_Pacote()
        {
            this.GRD_Turma_Pacote = new HashSet<GRD_Turma_Pacote>();
            this.Products = new HashSet<Products>();
            this.GRD_Aluno_Pacote = new HashSet<GRD_Aluno_Pacote>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDefault { get; set; }
        public int Ordem { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<GRD_Turma_Pacote> GRD_Turma_Pacote { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<GRD_Aluno_Pacote> GRD_Aluno_Pacote { get; set; }
    }
}
