//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Status
    {
        public GRD_Status()
        {
            this.GRD_Agendamento = new HashSet<GRD_Agendamento>();
            this.GRD_Prospect = new HashSet<GRD_Prospect>();
        }
    
        public int ID { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<GRD_Agendamento> GRD_Agendamento { get; set; }
        public virtual ICollection<GRD_Prospect> GRD_Prospect { get; set; }
    }
}
