//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Prospect
    {
        public int ID { get; set; }
        public int AlunoTurmaID { get; set; }
        public int VendedorID { get; set; }
        public System.DateTime Data { get; set; }
        public int Status { get; set; }
        public decimal TotalValue { get; set; }
        public string Descricao { get; set; }
    
        public virtual GRD_Status GRD_Status { get; set; }
        public virtual GRD_Vendedor GRD_Vendedor { get; set; }
    }
}
