//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_PessoaJuridica
    {
        public GRD_PessoaJuridica()
        {
            this.GRD_Company = new HashSet<GRD_Company>();
        }
    
        public int ID { get; set; }
        public string CNPJ { get; set; }
        public string NomeFantasia { get; set; }
        public string RazaoSocial { get; set; }
        public string Site { get; set; }
        public string Facebook { get; set; }
        public string Telefone { get; set; }
        public string InscricaoEstadual { get; set; }
        public string InscricaoMunicipal { get; set; }
        public Nullable<int> GRDAddressID { get; set; }
        public System.DateTime IncludeDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual GRD_Address GRD_Address { get; set; }
        public virtual ICollection<GRD_Company> GRD_Company { get; set; }
    }
}
