//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_OrderRequest
    {
        public GRD_OrderRequest()
        {
            this.GRD_Boleto = new HashSet<GRD_Boleto>();
            this.GRD_Cheque = new HashSet<GRD_Cheque>();
        }
    
        public int ID { get; set; }
        public int AlunoTurmaID { get; set; }
        public Nullable<int> VendedorID { get; set; }
        public System.DateTime Data { get; set; }
        public int PaymentTypeGroupID { get; set; }
        public int Parcelas { get; set; }
        public int OrderID { get; set; }
        public int OrigemID { get; set; }
        public string Observacao { get; set; }
    
        public virtual ICollection<GRD_Boleto> GRD_Boleto { get; set; }
        public virtual ICollection<GRD_Cheque> GRD_Cheque { get; set; }
        public virtual GRD_Vendedor GRD_Vendedor { get; set; }
        public virtual PaymentTypeGroup PaymentTypeGroup { get; set; }
    }
}
