//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Vendedor
    {
        public GRD_Vendedor()
        {
            this.GRD_Agendamento = new HashSet<GRD_Agendamento>();
            this.GRD_Aluno_Turma = new HashSet<GRD_Aluno_Turma>();
            this.GRD_OrderRequest = new HashSet<GRD_OrderRequest>();
            this.GRD_Prospect = new HashSet<GRD_Prospect>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Nome { get; set; }
        public int CompanyID { get; set; }
        public int PessoaFisicaID { get; set; }
        public double TxComissao { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DtDeleted { get; set; }
        public Nullable<int> VendedorIDCP7 { get; set; }
    
        public virtual ICollection<GRD_Agendamento> GRD_Agendamento { get; set; }
        public virtual ICollection<GRD_Aluno_Turma> GRD_Aluno_Turma { get; set; }
        public virtual GRD_Company GRD_Company { get; set; }
        public virtual ICollection<GRD_OrderRequest> GRD_OrderRequest { get; set; }
        public virtual GRD_PessoaFisica GRD_PessoaFisica { get; set; }
        public virtual ICollection<GRD_Prospect> GRD_Prospect { get; set; }
        public virtual Users Users { get; set; }
    }
}
