//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Aluno
    {
        public GRD_Aluno()
        {
            this.GRD_Aluno_Turma = new HashSet<GRD_Aluno_Turma>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public int PessoaFisicaID { get; set; }
        public string CodigoAluno { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DtDeleted { get; set; }
    
        public virtual GRD_PessoaFisica GRD_PessoaFisica { get; set; }
        public virtual ICollection<GRD_Aluno_Turma> GRD_Aluno_Turma { get; set; }
    }
}
