//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Turma_Pacote
    {
        public int GRD_PacoteID { get; set; }
        public int GRD_TurmaID { get; set; }
        public int Ordem { get; set; }
    
        public virtual GRD_Pacote GRD_Pacote { get; set; }
        public virtual GRD_Turma GRD_Turma { get; set; }
    }
}
