//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Turma
    {
        public GRD_Turma()
        {
            this.GRD_Aluno_Turma = new HashSet<GRD_Aluno_Turma>();
            this.GRD_Turma_Preco = new HashSet<GRD_Turma_Preco>();
            this.GRD_Turma_Pacote = new HashSet<GRD_Turma_Pacote>();
        }
    
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public string Nome { get; set; }
        public string Curso { get; set; }
        public string Faculdade { get; set; }
        public string SiglaFaculdade { get; set; }
        public int Ano { get; set; }
        public int Periodo { get; set; }
        public string CodigoTurma { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DtDeleted { get; set; }
        public string PIT { get; set; }
        public int OrigemID { get; set; }
    
        public virtual ICollection<GRD_Aluno_Turma> GRD_Aluno_Turma { get; set; }
        public virtual GRD_Company GRD_Company { get; set; }
        public virtual ICollection<GRD_Turma_Preco> GRD_Turma_Preco { get; set; }
        public virtual ICollection<GRD_Turma_Pacote> GRD_Turma_Pacote { get; set; }
    }
}
