//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_PessoaFisica
    {
        public GRD_PessoaFisica()
        {
            this.GRD_Company = new HashSet<GRD_Company>();
            this.GRD_Aluno = new HashSet<GRD_Aluno>();
            this.GRD_Vendedor = new HashSet<GRD_Vendedor>();
        }
    
        public int ID { get; set; }
        public string CPF { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Identidade { get; set; }
        public string OrgaoEmissor { get; set; }
        public System.DateTime DataEmissao { get; set; }
        public System.DateTime DtNascimento { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> GRDAddressID { get; set; }
        public System.DateTime IncludeDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual GRD_Address GRD_Address { get; set; }
        public virtual ICollection<GRD_Company> GRD_Company { get; set; }
        public virtual ICollection<GRD_Aluno> GRD_Aluno { get; set; }
        public virtual ICollection<GRD_Vendedor> GRD_Vendedor { get; set; }
    }
}
