//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Order_Product
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public int AlunoTurmaID { get; set; }
        public int Qtd { get; set; }
        public int QtdFoto { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual GRD_Aluno_Turma GRD_Aluno_Turma { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
