//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Boleto
    {
        public int ID { get; set; }
        public int AlunoTurmaID { get; set; }
        public int OrderRequestID { get; set; }
        public int OrderID { get; set; }
        public int Parcela { get; set; }
        public string NossoNumero { get; set; }
        public string NumeroDocumento { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public System.DateTime DataPagamento { get; set; }
        public Nullable<decimal> ValorPagamento { get; set; }
    
        public virtual GRD_Aluno_Turma GRD_Aluno_Turma { get; set; }
        public virtual GRD_OrderRequest GRD_OrderRequest { get; set; }
    }
}
