//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRD_Company
    {
        public GRD_Company()
        {
            this.GRD_Product_Config = new HashSet<GRD_Product_Config>();
            this.GRD_Turma = new HashSet<GRD_Turma>();
            this.GRD_Vendedor = new HashSet<GRD_Vendedor>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public string EntityType { get; set; }
        public string Name { get; set; }
        public Nullable<int> PessoaFisicaID { get; set; }
        public Nullable<int> PessoaJuridicaID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DtDeleted { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual GRD_PessoaFisica GRD_PessoaFisica { get; set; }
        public virtual GRD_PessoaJuridica GRD_PessoaJuridica { get; set; }
        public virtual ICollection<GRD_Product_Config> GRD_Product_Config { get; set; }
        public virtual ICollection<GRD_Turma> GRD_Turma { get; set; }
        public virtual ICollection<GRD_Vendedor> GRD_Vendedor { get; set; }
    }
}
