//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INodes
    {
        public INodes()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int inode_id { get; set; }
        public decimal size { get; set; }
        public decimal width { get; set; }
        public decimal height { get; set; }
        public string path { get; set; }
        public System.DateTime creation_date { get; set; }
        public string thumbnail_path { get; set; }
        public string main_photo_path { get; set; }
        public string wap_photo_path { get; set; }
        public string mmsLargePhotoPath { get; set; }
        public string mmsSmallPhotoPath { get; set; }
        public Nullable<int> drive_id { get; set; }
        public Nullable<int> max_resolution_id { get; set; }
    
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual InodesThumb InodesThumb { get; set; }
    }
}
