//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InodesThumb
    {
        public int InodeID { get; set; }
        public string bookPhotoPath { get; set; }
    
        public virtual INodes INodes { get; set; }
    }
}
