//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_payment_relation
    {
        public int orderid { get; set; }
        public int type { get; set; }
        public string cod_transacao { get; set; }
        public Nullable<int> sequencial { get; set; }
        public Nullable<decimal> value { get; set; }
        public string verified { get; set; }
        public string itau_payment_type { get; set; }
        public Nullable<int> bb_payment_status { get; set; }
        public string token { get; set; }
        public Nullable<int> bradesco_payment_status { get; set; }
        public string cod_confirm_bradesco { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
    }
}
