//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTypeGroup
    {
        public PaymentTypeGroup()
        {
            this.PaymentType = new HashSet<PaymentType>();
            this.GRD_OrderRequest = new HashSet<GRD_OrderRequest>();
        }
    
        public int id { get; set; }
        public string chave { get; set; }
        public string descricao { get; set; }
        public decimal valor_minimo { get; set; }
    
        public virtual ICollection<PaymentType> PaymentType { get; set; }
        public virtual ICollection<GRD_OrderRequest> GRD_OrderRequest { get; set; }
    }
}
