//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.order_payment_relation = new HashSet<order_payment_relation>();
        }
    
        public int id { get; set; }
        public string desc { get; set; }
        public string titulo { get; set; }
        public Nullable<int> PaymentTypeGroup { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual ICollection<order_payment_relation> order_payment_relation { get; set; }
        public virtual PaymentTypeGroup PaymentTypeGroup1 { get; set; }
    }
}
