//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public Photos()
        {
            this.albums = new HashSet<albums>();
            this.albums1 = new HashSet<albums>();
            this.GRD_Order_Product_Photos = new HashSet<GRD_Order_Product_Photos>();
            this.GRD_AlunoTurma_Photos = new HashSet<GRD_AlunoTurma_Photos>();
        }
    
        public int photo_id { get; set; }
        public int inode_id { get; set; }
        public Nullable<int> partner_id { get; set; }
        public string photo_partner_id { get; set; }
        public int author_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> origin_shop_id { get; set; }
        public string photo_desc { get; set; }
        public Nullable<System.DateTime> photo_date { get; set; }
        public string participants { get; set; }
        public Nullable<int> is_quota_counted { get; set; }
        public Nullable<int> album_id { get; set; }
        public Nullable<System.DateTime> deletion_date { get; set; }
        public Nullable<System.DateTime> dt_ultima_visualizacao { get; set; }
        public string fl_effect { get; set; }
    
        public virtual ICollection<albums> albums { get; set; }
        public virtual INodes INodes { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<albums> albums1 { get; set; }
        public virtual ICollection<GRD_Order_Product_Photos> GRD_Order_Product_Photos { get; set; }
        public virtual ICollection<GRD_AlunoTurma_Photos> GRD_AlunoTurma_Photos { get; set; }
    }
}
