//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PixelHouseDBEntities : DbContext
    {
        public PixelHouseDBEntities()
            : base("name=PixelHouseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Products> Products { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<CART_LOG_REFRESH_CACHE> CART_LOG_REFRESH_CACHE { get; set; }
        public DbSet<FB_UserToken> FB_UserToken { get; set; }
        public DbSet<V_NICKNAME_USER> V_NICKNAME_USER { get; set; }
        public DbSet<FB_Photobook> FB_Photobook { get; set; }
        public DbSet<v_Informacoes_Photobook_Formatura> v_Informacoes_Photobook_Formatura { get; set; }
        public DbSet<v_products> v_products { get; set; }
        public DbSet<Brand> Brand { get; set; }
        public DbSet<template_email_mkt> template_email_mkt { get; set; }
        public DbSet<User_Forgot_Password> User_Forgot_Password { get; set; }
        public DbSet<user_account_transaction_history> user_account_transaction_history { get; set; }
        public DbSet<usuario_acesso> usuario_acesso { get; set; }
        public DbSet<albums> albums { get; set; }
        public DbSet<INodes> INodes { get; set; }
        public DbSet<Photos> Photos { get; set; }
        public DbSet<InodesThumb> InodesThumb { get; set; }
        public DbSet<GRD_Address> GRD_Address { get; set; }
        public DbSet<GRD_Company> GRD_Company { get; set; }
        public DbSet<GRD_PessoaFisica> GRD_PessoaFisica { get; set; }
        public DbSet<GRD_PessoaJuridica> GRD_PessoaJuridica { get; set; }
        public DbSet<v_GRD_ListaUsuarios> v_GRD_ListaUsuarios { get; set; }
        public DbSet<GRD_Agendamento> GRD_Agendamento { get; set; }
        public DbSet<GRD_Status> GRD_Status { get; set; }
        public DbSet<order_payment_relation> order_payment_relation { get; set; }
        public DbSet<PaymentType> PaymentType { get; set; }
        public DbSet<PaymentTypeGroup> PaymentTypeGroup { get; set; }
        public DbSet<GRD_Cart_Product> GRD_Cart_Product { get; set; }
        public DbSet<v_GRD_Products> v_GRD_Products { get; set; }
        public DbSet<GRD_Order_Product_Photos> GRD_Order_Product_Photos { get; set; }
        public DbSet<GRD_AlunoTurma_Photos> GRD_AlunoTurma_Photos { get; set; }
        public DbSet<GRD_Aluno> GRD_Aluno { get; set; }
        public DbSet<GRD_Aluno_Turma> GRD_Aluno_Turma { get; set; }
        public DbSet<GRD_AlunoTurma_Album> GRD_AlunoTurma_Album { get; set; }
        public DbSet<GRD_AlunoTurma_Book> GRD_AlunoTurma_Book { get; set; }
        public DbSet<GRD_Boleto> GRD_Boleto { get; set; }
        public DbSet<GRD_Cheque> GRD_Cheque { get; set; }
        public DbSet<GRD_Process_Upload> GRD_Process_Upload { get; set; }
        public DbSet<GRD_Product_Config> GRD_Product_Config { get; set; }
        public DbSet<GRD_Prospect> GRD_Prospect { get; set; }
        public DbSet<GRD_Turma> GRD_Turma { get; set; }
        public DbSet<GRD_Turma_Preco> GRD_Turma_Preco { get; set; }
        public DbSet<GRD_Turma_Preco_Hist> GRD_Turma_Preco_Hist { get; set; }
        public DbSet<v_GRD_TabelaPreco> v_GRD_TabelaPreco { get; set; }
        public DbSet<v_CartoesAceitos> v_CartoesAceitos { get; set; }
        public DbSet<GRD_Order_Product> GRD_Order_Product { get; set; }
        public DbSet<GRD_Frete_Hist> GRD_Frete_Hist { get; set; }
        public DbSet<GRD_OrderRequest> GRD_OrderRequest { get; set; }
        public DbSet<GRD_Vendedor> GRD_Vendedor { get; set; }
        public DbSet<GRD_Pacote> GRD_Pacote { get; set; }
        public DbSet<GRD_Turma_Pacote> GRD_Turma_Pacote { get; set; }
        public DbSet<GRD_Aluno_Pacote> GRD_Aluno_Pacote { get; set; }
        public DbSet<GRD_DadosComprador> GRD_DadosComprador { get; set; }
    
        public virtual ObjectResult<PR_USER_ALTERA_SENHA_Result> PR_USER_ALTERA_SENHA(Nullable<int> uSER_ID, string sENHA_NOVA_ENCRIPTADA)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            var sENHA_NOVA_ENCRIPTADAParameter = sENHA_NOVA_ENCRIPTADA != null ?
                new ObjectParameter("SENHA_NOVA_ENCRIPTADA", sENHA_NOVA_ENCRIPTADA) :
                new ObjectParameter("SENHA_NOVA_ENCRIPTADA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_USER_ALTERA_SENHA_Result>("PR_USER_ALTERA_SENHA", uSER_IDParameter, sENHA_NOVA_ENCRIPTADAParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pr_mob_user_insert(string email, Nullable<int> brand_id, string password, string name, string lastname, Nullable<System.DateTime> birth_date, string genre, Nullable<byte> accept_newsletter, Nullable<byte> accept_promot_info, string telefone, string origem, string faceBookID, string faceBookEmail)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var brand_idParameter = brand_id.HasValue ?
                new ObjectParameter("brand_id", brand_id) :
                new ObjectParameter("brand_id", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var birth_dateParameter = birth_date.HasValue ?
                new ObjectParameter("birth_date", birth_date) :
                new ObjectParameter("birth_date", typeof(System.DateTime));
    
            var genreParameter = genre != null ?
                new ObjectParameter("genre", genre) :
                new ObjectParameter("genre", typeof(string));
    
            var accept_newsletterParameter = accept_newsletter.HasValue ?
                new ObjectParameter("accept_newsletter", accept_newsletter) :
                new ObjectParameter("accept_newsletter", typeof(byte));
    
            var accept_promot_infoParameter = accept_promot_info.HasValue ?
                new ObjectParameter("accept_promot_info", accept_promot_info) :
                new ObjectParameter("accept_promot_info", typeof(byte));
    
            var telefoneParameter = telefone != null ?
                new ObjectParameter("telefone", telefone) :
                new ObjectParameter("telefone", typeof(string));
    
            var origemParameter = origem != null ?
                new ObjectParameter("origem", origem) :
                new ObjectParameter("origem", typeof(string));
    
            var faceBookIDParameter = faceBookID != null ?
                new ObjectParameter("FaceBookID", faceBookID) :
                new ObjectParameter("FaceBookID", typeof(string));
    
            var faceBookEmailParameter = faceBookEmail != null ?
                new ObjectParameter("FaceBookEmail", faceBookEmail) :
                new ObjectParameter("FaceBookEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pr_mob_user_insert", emailParameter, brand_idParameter, passwordParameter, nameParameter, lastnameParameter, birth_dateParameter, genreParameter, accept_newsletterParameter, accept_promot_infoParameter, telefoneParameter, origemParameter, faceBookIDParameter, faceBookEmailParameter);
        }
    
        public virtual ObjectResult<PR_GRD_CADASTRAR_USUARIO_PF_Result> PR_GRD_CADASTRAR_USUARIO_PF(string cPF, string rG, string nome, string telefone, string email, string senhaEncryptada, string orgaoEmissor, Nullable<System.DateTime> dataEmissao, Nullable<System.DateTime> dtNascimento, string sexo, Nullable<int> brand_ID, string endereco, string endereco_Numero, string endereco_Complemento, string endereco_Bairro, string endereco_Cidade, string endereco_Estado, string cEP)
        {
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            var rGParameter = rG != null ?
                new ObjectParameter("RG", rG) :
                new ObjectParameter("RG", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var telefoneParameter = telefone != null ?
                new ObjectParameter("Telefone", telefone) :
                new ObjectParameter("Telefone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var senhaEncryptadaParameter = senhaEncryptada != null ?
                new ObjectParameter("SenhaEncryptada", senhaEncryptada) :
                new ObjectParameter("SenhaEncryptada", typeof(string));
    
            var orgaoEmissorParameter = orgaoEmissor != null ?
                new ObjectParameter("OrgaoEmissor", orgaoEmissor) :
                new ObjectParameter("OrgaoEmissor", typeof(string));
    
            var dataEmissaoParameter = dataEmissao.HasValue ?
                new ObjectParameter("DataEmissao", dataEmissao) :
                new ObjectParameter("DataEmissao", typeof(System.DateTime));
    
            var dtNascimentoParameter = dtNascimento.HasValue ?
                new ObjectParameter("DtNascimento", dtNascimento) :
                new ObjectParameter("DtNascimento", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var brand_IDParameter = brand_ID.HasValue ?
                new ObjectParameter("Brand_ID", brand_ID) :
                new ObjectParameter("Brand_ID", typeof(int));
    
            var enderecoParameter = endereco != null ?
                new ObjectParameter("Endereco", endereco) :
                new ObjectParameter("Endereco", typeof(string));
    
            var endereco_NumeroParameter = endereco_Numero != null ?
                new ObjectParameter("Endereco_Numero", endereco_Numero) :
                new ObjectParameter("Endereco_Numero", typeof(string));
    
            var endereco_ComplementoParameter = endereco_Complemento != null ?
                new ObjectParameter("Endereco_Complemento", endereco_Complemento) :
                new ObjectParameter("Endereco_Complemento", typeof(string));
    
            var endereco_BairroParameter = endereco_Bairro != null ?
                new ObjectParameter("Endereco_Bairro", endereco_Bairro) :
                new ObjectParameter("Endereco_Bairro", typeof(string));
    
            var endereco_CidadeParameter = endereco_Cidade != null ?
                new ObjectParameter("Endereco_Cidade", endereco_Cidade) :
                new ObjectParameter("Endereco_Cidade", typeof(string));
    
            var endereco_EstadoParameter = endereco_Estado != null ?
                new ObjectParameter("Endereco_Estado", endereco_Estado) :
                new ObjectParameter("Endereco_Estado", typeof(string));
    
            var cEPParameter = cEP != null ?
                new ObjectParameter("CEP", cEP) :
                new ObjectParameter("CEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GRD_CADASTRAR_USUARIO_PF_Result>("PR_GRD_CADASTRAR_USUARIO_PF", cPFParameter, rGParameter, nomeParameter, telefoneParameter, emailParameter, senhaEncryptadaParameter, orgaoEmissorParameter, dataEmissaoParameter, dtNascimentoParameter, sexoParameter, brand_IDParameter, enderecoParameter, endereco_NumeroParameter, endereco_ComplementoParameter, endereco_BairroParameter, endereco_CidadeParameter, endereco_EstadoParameter, cEPParameter);
        }
    
        public virtual ObjectResult<PR_GRD_CADASTRAR_USUARIO_PJ_C_Result> PR_GRD_CADASTRAR_USUARIO_PJ_C(string nomeFantasia, string nomeUsuario, string sexoUsuario, string email, string razaoSocial, string site, string cNPJ, string facebook, string telefone, string inscricaoEstadual, string inscricaoMunicipal, string senhaEncryptada, Nullable<System.DateTime> dtNascimento, Nullable<int> brand_ID, string endereco, string endereco_Numero, string endereco_Complemento, string endereco_Bairro, string endereco_Cidade, string endereco_Estado, string cEP)
        {
            var nomeFantasiaParameter = nomeFantasia != null ?
                new ObjectParameter("NomeFantasia", nomeFantasia) :
                new ObjectParameter("NomeFantasia", typeof(string));
    
            var nomeUsuarioParameter = nomeUsuario != null ?
                new ObjectParameter("NomeUsuario", nomeUsuario) :
                new ObjectParameter("NomeUsuario", typeof(string));
    
            var sexoUsuarioParameter = sexoUsuario != null ?
                new ObjectParameter("SexoUsuario", sexoUsuario) :
                new ObjectParameter("SexoUsuario", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var razaoSocialParameter = razaoSocial != null ?
                new ObjectParameter("RazaoSocial", razaoSocial) :
                new ObjectParameter("RazaoSocial", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var cNPJParameter = cNPJ != null ?
                new ObjectParameter("CNPJ", cNPJ) :
                new ObjectParameter("CNPJ", typeof(string));
    
            var facebookParameter = facebook != null ?
                new ObjectParameter("Facebook", facebook) :
                new ObjectParameter("Facebook", typeof(string));
    
            var telefoneParameter = telefone != null ?
                new ObjectParameter("Telefone", telefone) :
                new ObjectParameter("Telefone", typeof(string));
    
            var inscricaoEstadualParameter = inscricaoEstadual != null ?
                new ObjectParameter("InscricaoEstadual", inscricaoEstadual) :
                new ObjectParameter("InscricaoEstadual", typeof(string));
    
            var inscricaoMunicipalParameter = inscricaoMunicipal != null ?
                new ObjectParameter("InscricaoMunicipal", inscricaoMunicipal) :
                new ObjectParameter("InscricaoMunicipal", typeof(string));
    
            var senhaEncryptadaParameter = senhaEncryptada != null ?
                new ObjectParameter("SenhaEncryptada", senhaEncryptada) :
                new ObjectParameter("SenhaEncryptada", typeof(string));
    
            var dtNascimentoParameter = dtNascimento.HasValue ?
                new ObjectParameter("DtNascimento", dtNascimento) :
                new ObjectParameter("DtNascimento", typeof(System.DateTime));
    
            var brand_IDParameter = brand_ID.HasValue ?
                new ObjectParameter("Brand_ID", brand_ID) :
                new ObjectParameter("Brand_ID", typeof(int));
    
            var enderecoParameter = endereco != null ?
                new ObjectParameter("Endereco", endereco) :
                new ObjectParameter("Endereco", typeof(string));
    
            var endereco_NumeroParameter = endereco_Numero != null ?
                new ObjectParameter("Endereco_Numero", endereco_Numero) :
                new ObjectParameter("Endereco_Numero", typeof(string));
    
            var endereco_ComplementoParameter = endereco_Complemento != null ?
                new ObjectParameter("Endereco_Complemento", endereco_Complemento) :
                new ObjectParameter("Endereco_Complemento", typeof(string));
    
            var endereco_BairroParameter = endereco_Bairro != null ?
                new ObjectParameter("Endereco_Bairro", endereco_Bairro) :
                new ObjectParameter("Endereco_Bairro", typeof(string));
    
            var endereco_CidadeParameter = endereco_Cidade != null ?
                new ObjectParameter("Endereco_Cidade", endereco_Cidade) :
                new ObjectParameter("Endereco_Cidade", typeof(string));
    
            var endereco_EstadoParameter = endereco_Estado != null ?
                new ObjectParameter("Endereco_Estado", endereco_Estado) :
                new ObjectParameter("Endereco_Estado", typeof(string));
    
            var cEPParameter = cEP != null ?
                new ObjectParameter("CEP", cEP) :
                new ObjectParameter("CEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GRD_CADASTRAR_USUARIO_PJ_C_Result>("PR_GRD_CADASTRAR_USUARIO_PJ_C", nomeFantasiaParameter, nomeUsuarioParameter, sexoUsuarioParameter, emailParameter, razaoSocialParameter, siteParameter, cNPJParameter, facebookParameter, telefoneParameter, inscricaoEstadualParameter, inscricaoMunicipalParameter, senhaEncryptadaParameter, dtNascimentoParameter, brand_IDParameter, enderecoParameter, endereco_NumeroParameter, endereco_ComplementoParameter, endereco_BairroParameter, endereco_CidadeParameter, endereco_EstadoParameter, cEPParameter);
        }
    
        public virtual ObjectResult<PR_GRD_CADASTRAR_USUARIO_PJ_U_Result> PR_GRD_CADASTRAR_USUARIO_PJ_U(Nullable<int> gRD_Company_ID, string nomeUsuario, Nullable<System.DateTime> dtNascimento, string sexoUsuario, string email, string senhaEncryptada, Nullable<int> brand_ID)
        {
            var gRD_Company_IDParameter = gRD_Company_ID.HasValue ?
                new ObjectParameter("GRD_Company_ID", gRD_Company_ID) :
                new ObjectParameter("GRD_Company_ID", typeof(int));
    
            var nomeUsuarioParameter = nomeUsuario != null ?
                new ObjectParameter("NomeUsuario", nomeUsuario) :
                new ObjectParameter("NomeUsuario", typeof(string));
    
            var dtNascimentoParameter = dtNascimento.HasValue ?
                new ObjectParameter("DtNascimento", dtNascimento) :
                new ObjectParameter("DtNascimento", typeof(System.DateTime));
    
            var sexoUsuarioParameter = sexoUsuario != null ?
                new ObjectParameter("SexoUsuario", sexoUsuario) :
                new ObjectParameter("SexoUsuario", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var senhaEncryptadaParameter = senhaEncryptada != null ?
                new ObjectParameter("SenhaEncryptada", senhaEncryptada) :
                new ObjectParameter("SenhaEncryptada", typeof(string));
    
            var brand_IDParameter = brand_ID.HasValue ?
                new ObjectParameter("Brand_ID", brand_ID) :
                new ObjectParameter("Brand_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GRD_CADASTRAR_USUARIO_PJ_U_Result>("PR_GRD_CADASTRAR_USUARIO_PJ_U", gRD_Company_IDParameter, nomeUsuarioParameter, dtNascimentoParameter, sexoUsuarioParameter, emailParameter, senhaEncryptadaParameter, brand_IDParameter);
        }
    
        public virtual ObjectResult<pr_GRD_ProductsAluno_Result> pr_GRD_ProductsAluno(Nullable<int> alunoTurmaID)
        {
            var alunoTurmaIDParameter = alunoTurmaID.HasValue ?
                new ObjectParameter("AlunoTurmaID", alunoTurmaID) :
                new ObjectParameter("AlunoTurmaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GRD_ProductsAluno_Result>("pr_GRD_ProductsAluno", alunoTurmaIDParameter);
        }
    
        public virtual ObjectResult<pr_GRD_AlunoUpload_Result> pr_GRD_AlunoUpload(string pIT, string alunoID, Nullable<int> userIDMaster)
        {
            var pITParameter = pIT != null ?
                new ObjectParameter("PIT", pIT) :
                new ObjectParameter("PIT", typeof(string));
    
            var alunoIDParameter = alunoID != null ?
                new ObjectParameter("AlunoID", alunoID) :
                new ObjectParameter("AlunoID", typeof(string));
    
            var userIDMasterParameter = userIDMaster.HasValue ?
                new ObjectParameter("UserIDMaster", userIDMaster) :
                new ObjectParameter("UserIDMaster", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GRD_AlunoUpload_Result>("pr_GRD_AlunoUpload", pITParameter, alunoIDParameter, userIDMasterParameter);
        }
    
        public virtual int pr_GRD_CreatePhoto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_GRD_CreatePhoto");
        }
    
        public virtual ObjectResult<pr_GRD_PopulaTurmaAluno_Result> pr_GRD_PopulaTurmaAluno(string title, string addressLine, string addressNumber, string addressComplement, string neighbourhood, string city, string state, string country, string zipCode, string cPF, string nome, string telefone, string email, string identidade, string orgaoEmissor, Nullable<System.DateTime> dataEmissao, Nullable<System.DateTime> dtNascimento, string sexo, Nullable<int> companyID, string nomeTurma, string curso, string faculdade, string siglaFaculdade, Nullable<int> ano, Nullable<int> periodo, string codigoTurma, string pIT, Nullable<int> vendedorID, string codigoCP7, string iDInternoCP7, string codigoAlunoTurma, Nullable<int> origemID, Nullable<int> productID)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var addressLineParameter = addressLine != null ?
                new ObjectParameter("AddressLine", addressLine) :
                new ObjectParameter("AddressLine", typeof(string));
    
            var addressNumberParameter = addressNumber != null ?
                new ObjectParameter("AddressNumber", addressNumber) :
                new ObjectParameter("AddressNumber", typeof(string));
    
            var addressComplementParameter = addressComplement != null ?
                new ObjectParameter("AddressComplement", addressComplement) :
                new ObjectParameter("AddressComplement", typeof(string));
    
            var neighbourhoodParameter = neighbourhood != null ?
                new ObjectParameter("Neighbourhood", neighbourhood) :
                new ObjectParameter("Neighbourhood", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("ZipCode", zipCode) :
                new ObjectParameter("ZipCode", typeof(string));
    
            var cPFParameter = cPF != null ?
                new ObjectParameter("CPF", cPF) :
                new ObjectParameter("CPF", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var telefoneParameter = telefone != null ?
                new ObjectParameter("Telefone", telefone) :
                new ObjectParameter("Telefone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var identidadeParameter = identidade != null ?
                new ObjectParameter("Identidade", identidade) :
                new ObjectParameter("Identidade", typeof(string));
    
            var orgaoEmissorParameter = orgaoEmissor != null ?
                new ObjectParameter("OrgaoEmissor", orgaoEmissor) :
                new ObjectParameter("OrgaoEmissor", typeof(string));
    
            var dataEmissaoParameter = dataEmissao.HasValue ?
                new ObjectParameter("DataEmissao", dataEmissao) :
                new ObjectParameter("DataEmissao", typeof(System.DateTime));
    
            var dtNascimentoParameter = dtNascimento.HasValue ?
                new ObjectParameter("DtNascimento", dtNascimento) :
                new ObjectParameter("DtNascimento", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var nomeTurmaParameter = nomeTurma != null ?
                new ObjectParameter("NomeTurma", nomeTurma) :
                new ObjectParameter("NomeTurma", typeof(string));
    
            var cursoParameter = curso != null ?
                new ObjectParameter("Curso", curso) :
                new ObjectParameter("Curso", typeof(string));
    
            var faculdadeParameter = faculdade != null ?
                new ObjectParameter("Faculdade", faculdade) :
                new ObjectParameter("Faculdade", typeof(string));
    
            var siglaFaculdadeParameter = siglaFaculdade != null ?
                new ObjectParameter("SiglaFaculdade", siglaFaculdade) :
                new ObjectParameter("SiglaFaculdade", typeof(string));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(int));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            var codigoTurmaParameter = codigoTurma != null ?
                new ObjectParameter("CodigoTurma", codigoTurma) :
                new ObjectParameter("CodigoTurma", typeof(string));
    
            var pITParameter = pIT != null ?
                new ObjectParameter("PIT", pIT) :
                new ObjectParameter("PIT", typeof(string));
    
            var vendedorIDParameter = vendedorID.HasValue ?
                new ObjectParameter("VendedorID", vendedorID) :
                new ObjectParameter("VendedorID", typeof(int));
    
            var codigoCP7Parameter = codigoCP7 != null ?
                new ObjectParameter("CodigoCP7", codigoCP7) :
                new ObjectParameter("CodigoCP7", typeof(string));
    
            var iDInternoCP7Parameter = iDInternoCP7 != null ?
                new ObjectParameter("IDInternoCP7", iDInternoCP7) :
                new ObjectParameter("IDInternoCP7", typeof(string));
    
            var codigoAlunoTurmaParameter = codigoAlunoTurma != null ?
                new ObjectParameter("CodigoAlunoTurma", codigoAlunoTurma) :
                new ObjectParameter("CodigoAlunoTurma", typeof(string));
    
            var origemIDParameter = origemID.HasValue ?
                new ObjectParameter("OrigemID", origemID) :
                new ObjectParameter("OrigemID", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GRD_PopulaTurmaAluno_Result>("pr_GRD_PopulaTurmaAluno", titleParameter, addressLineParameter, addressNumberParameter, addressComplementParameter, neighbourhoodParameter, cityParameter, stateParameter, countryParameter, zipCodeParameter, cPFParameter, nomeParameter, telefoneParameter, emailParameter, identidadeParameter, orgaoEmissorParameter, dataEmissaoParameter, dtNascimentoParameter, sexoParameter, companyIDParameter, nomeTurmaParameter, cursoParameter, faculdadeParameter, siglaFaculdadeParameter, anoParameter, periodoParameter, codigoTurmaParameter, pITParameter, vendedorIDParameter, codigoCP7Parameter, iDInternoCP7Parameter, codigoAlunoTurmaParameter, origemIDParameter, productIDParameter);
        }
    
        public virtual ObjectResult<pr_GRD_SelectPhotoGroupProducts_Result> pr_GRD_SelectPhotoGroupProducts(Nullable<int> alunoTurmaID, Nullable<int> productID)
        {
            var alunoTurmaIDParameter = alunoTurmaID.HasValue ?
                new ObjectParameter("AlunoTurmaID", alunoTurmaID) :
                new ObjectParameter("AlunoTurmaID", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GRD_SelectPhotoGroupProducts_Result>("pr_GRD_SelectPhotoGroupProducts", alunoTurmaIDParameter, productIDParameter);
        }
    
        public virtual int pr_GRD_UpdateProcessUpload(Nullable<int> iD, string status, string msg)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var msgParameter = msg != null ?
                new ObjectParameter("Msg", msg) :
                new ObjectParameter("Msg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_GRD_UpdateProcessUpload", iDParameter, statusParameter, msgParameter);
        }
    
        public virtual ObjectResult<string> PR_PIX_ObtemPerfilUsuario(Nullable<int> uSER_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PR_PIX_ObtemPerfilUsuario", uSER_IDParameter);
        }
    
        public virtual ObjectResult<string> pr_orders_get_boleto_id(Nullable<int> order_id, Nullable<decimal> total_value, ObjectParameter boleto_id, ObjectParameter dt_vct)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var total_valueParameter = total_value.HasValue ?
                new ObjectParameter("total_value", total_value) :
                new ObjectParameter("total_value", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_orders_get_boleto_id", order_idParameter, total_valueParameter, boleto_id, dt_vct);
        }
    
        public virtual ObjectResult<pr_GRD_SaveTurmaAlunoPorFora_Result> pr_GRD_SaveTurmaAlunoPorFora(Nullable<int> alunoTurmaID, Nullable<int> userID, string pIT, string nome, Nullable<int> albumID, Nullable<int> orderID, Nullable<int> bookID)
        {
            var alunoTurmaIDParameter = alunoTurmaID.HasValue ?
                new ObjectParameter("AlunoTurmaID", alunoTurmaID) :
                new ObjectParameter("AlunoTurmaID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var pITParameter = pIT != null ?
                new ObjectParameter("PIT", pIT) :
                new ObjectParameter("PIT", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var albumIDParameter = albumID.HasValue ?
                new ObjectParameter("AlbumID", albumID) :
                new ObjectParameter("AlbumID", typeof(int));
    
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var bookIDParameter = bookID.HasValue ?
                new ObjectParameter("BookID", bookID) :
                new ObjectParameter("BookID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GRD_SaveTurmaAlunoPorFora_Result>("pr_GRD_SaveTurmaAlunoPorFora", alunoTurmaIDParameter, userIDParameter, pITParameter, nomeParameter, albumIDParameter, orderIDParameter, bookIDParameter);
        }
    }
}
