//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.GRD_Cart_Product = new HashSet<GRD_Cart_Product>();
            this.GRD_Order_Product_Photos = new HashSet<GRD_Order_Product_Photos>();
            this.GRD_Product_Config = new HashSet<GRD_Product_Config>();
            this.GRD_Turma_Preco = new HashSet<GRD_Turma_Preco>();
            this.GRD_Order_Product = new HashSet<GRD_Order_Product>();
            this.GRD_Aluno_Turma = new HashSet<GRD_Aluno_Turma>();
            this.GRD_Pacote = new HashSet<GRD_Pacote>();
        }
    
        public int product_id { get; set; }
        public string product_type { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
        public double discount { get; set; }
        public Nullable<int> group_id { get; set; }
        public string cod_size { get; set; }
        public string des_size { get; set; }
        public string des_medidas { get; set; }
        public string fl_active { get; set; }
        public bool fl_promo_allowed { get; set; }
        public bool fl_offer_allowed { get; set; }
        public int photos_capacity { get; set; }
        public bool isPortifolio { get; set; }
    
        public virtual ICollection<GRD_Cart_Product> GRD_Cart_Product { get; set; }
        public virtual ICollection<GRD_Order_Product_Photos> GRD_Order_Product_Photos { get; set; }
        public virtual ICollection<GRD_Product_Config> GRD_Product_Config { get; set; }
        public virtual ICollection<GRD_Turma_Preco> GRD_Turma_Preco { get; set; }
        public virtual ICollection<GRD_Order_Product> GRD_Order_Product { get; set; }
        public virtual ICollection<GRD_Aluno_Turma> GRD_Aluno_Turma { get; set; }
        public virtual ICollection<GRD_Pacote> GRD_Pacote { get; set; }
    }
}
