//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class template_email_mkt
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public string html { get; set; }
        public Nullable<int> promotion_id { get; set; }
        public string assunto { get; set; }
    }
}
