//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_account_transaction_history
    {
        public int id { get; set; }
        public int userID { get; set; }
        public string description { get; set; }
        public decimal vlr { get; set; }
        public System.DateTime dtInclude { get; set; }
        public int accountHistoryID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
