//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.User_Forgot_Password = new HashSet<User_Forgot_Password>();
            this.user_account_transaction_history = new HashSet<user_account_transaction_history>();
            this.albums = new HashSet<albums>();
            this.Photos = new HashSet<Photos>();
            this.Brand1 = new HashSet<Brand>();
            this.GRD_Cart_Product = new HashSet<GRD_Cart_Product>();
            this.GRD_Order_Product = new HashSet<GRD_Order_Product>();
            this.GRD_Vendedor = new HashSet<GRD_Vendedor>();
        }
    
        public int user_id { get; set; }
        public string email { get; set; }
        public string old_password { get; set; }
        public string name { get; set; }
        public string nick_name { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string genre { get; set; }
        public Nullable<byte> accept_Newsletter { get; set; }
        public Nullable<byte> accept_Promot_Info { get; set; }
        public string type { get; set; }
        public string telefone { get; set; }
        public string origem { get; set; }
        public string password { get; set; }
        public System.DateTime register_date { get; set; }
        public Nullable<System.DateTime> DtUltimoAcesso { get; set; }
        public Nullable<int> num_acessos { get; set; }
        public string fl_oi_bandalarga { get; set; }
        public string fl_ndr { get; set; }
        public string type_upload { get; set; }
        public Nullable<int> user_id_referral { get; set; }
        public byte fl_nova_politica_site { get; set; }
        public Nullable<int> isConfirmedByEmail { get; set; }
        public Nullable<int> brand_id { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<User_Forgot_Password> User_Forgot_Password { get; set; }
        public virtual ICollection<user_account_transaction_history> user_account_transaction_history { get; set; }
        public virtual ICollection<albums> albums { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual ICollection<Brand> Brand1 { get; set; }
        public virtual ICollection<GRD_Cart_Product> GRD_Cart_Product { get; set; }
        public virtual ICollection<GRD_Order_Product> GRD_Order_Product { get; set; }
        public virtual ICollection<GRD_Vendedor> GRD_Vendedor { get; set; }
    }
}
