//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_acesso
    {
        public int id_acesso { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> dt_acesso { get; set; }
        public string url_promocao { get; set; }
        public string ip_server { get; set; }
        public string remote_addr { get; set; }
    }
}
