//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GRD_ListaUsuarios
    {
        public int user_id { get; set; }
        public int CompanyID { get; set; }
        public int BrandID { get; set; }
        public Nullable<int> PessoaFisicaID { get; set; }
        public Nullable<int> PessoaJuridicaID { get; set; }
        public string EntityType { get; set; }
        public string NomeFantasia { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public Nullable<System.DateTime> DtUltimoAcesso { get; set; }
    }
}
