//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Informacoes_Photobook_Formatura
    {
        public int User_ID { get; set; }
        public int Book_ID { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Tipo_ID { get; set; }
        public int Product_ID { get; set; }
        public int Format_ID { get; set; }
        public int Size_ID { get; set; }
        public string Size_Description { get; set; }
        public int Pages { get; set; }
        public int Cover_ID { get; set; }
        public Nullable<int> Color_ID { get; set; }
        public int Paper_ID { get; set; }
        public int Step { get; set; }
        public decimal Preco { get; set; }
        public int Category_ID { get; set; }
        public string Category_Name { get; set; }
        public int Theme_ID { get; set; }
        public string Theme_Name { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
        public int Model_ID { get; set; }
        public int Tipo_Montagem { get; set; }
        public System.DateTime Data_Atualizacao { get; set; }
        public Nullable<System.DateTime> Data_Finalizacao { get; set; }
        public System.DateTime Data_Criacao { get; set; }
        public string Pedido_Codigo { get; set; }
        public Nullable<int> Pedido_ID { get; set; }
        public Nullable<int> Pedido_Status_ID { get; set; }
        public string Pedido_Status { get; set; }
        public Nullable<System.DateTime> Pedido_Data_Criacao { get; set; }
        public string Texto_Lombada { get; set; }
        public Nullable<int> Qtd_fotos { get; set; }
    }
}
