//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH.Formatura.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_products
    {
        public int Brand_ID { get; set; }
        public int product_id { get; set; }
        public string description { get; set; }
        public string product_type { get; set; }
        public string cod_size { get; set; }
        public string des_size { get; set; }
        public string des_medidas { get; set; }
        public string fl_active { get; set; }
        public bool fl_promo_allowed { get; set; }
        public bool fl_offer_allowed { get; set; }
        public int photos_capacity { get; set; }
        public Nullable<bool> isPortifolio { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Price_Extra_Page { get; set; }
        public int Scale_Mode_ID_Default { get; set; }
        public int order { get; set; }
        public string Url { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> PagesMax { get; set; }
        public Nullable<int> PagesMin { get; set; }
        public Nullable<int> PhotobookLineID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> shelfPhotobookID { get; set; }
    }
}
